### ISSUE TITLE
What happens when the JVM crashes?

### ISSUE THREAD

**Issue by floyd-fuh** [isstac/kelinci#1]
Hi Kody,

Amazing work and really nice approach to Java fuzzing! I just reproduced commons-imaging NegativeArraySizeException with the instructions in this github. After jumping through the usual hoops (wrong Java version, broken gradle in Ubuntu repositories, etc.) it was really easy. I wanted to let you know that first of all, it works perfectly fine on ARM machines as well (I ran everything on an odroid u3) and that afl-cmin and related tools work fine as well. Additionally, I think you either a) were not interested in finding a lot more bugs or b) you didn't use a good input corpus or c) I was lucky, however, I found some more issues within minutes (I have to investigate the first one more in-depth, but I guess that could at least lead to a DoS condition):

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at org.apache.commons.imaging.formats.jpeg.decoder.JpegDecoder.visitSOS(JpegDecoder.java:101)
	at org.apache.commons.imaging.formats.jpeg.JpegUtils.traverseJFIF(JpegUtils.java:77)
	at org.apache.commons.imaging.formats.jpeg.decoder.JpegDecoder.decode(JpegDecoder.java:437)
	at org.apache.commons.imaging.formats.jpeg.JpegImageParser.getBufferedImage(JpegImageParser.java:97)
	at driver.Driver.main(Driver.java:23)
```

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at org.apache.commons.imaging.formats.jpeg.segments.DhtSegment$HuffmanTable.<init>(DhtSegment.java:79)
	at org.apache.commons.imaging.formats.jpeg.segments.DhtSegment.<init>(DhtSegment.java:173)
	at org.apache.commons.imaging.formats.jpeg.segments.DhtSegment.<init>(DhtSegment.java:146)
	at org.apache.commons.imaging.formats.jpeg.decoder.JpegDecoder.visitSegment(JpegDecoder.java:219)
	at org.apache.commons.imaging.formats.jpeg.JpegUtils.traverseJFIF(JpegUtils.java:89)
	at org.apache.commons.imaging.formats.jpeg.decoder.JpegDecoder.decode(JpegDecoder.java:437)
	at org.apache.commons.imaging.formats.jpeg.JpegImageParser.getBufferedImage(JpegImageParser.java:97)
	at driver.Driver.main(Driver.java:23)
```

I also have a question: What would happen if the JVM crashes, would AFL detect it as a regular crash? Because I'm thinking about using this approach in combination with Java programs that use native interfaces, which might lead to crashes of the JVM.

Thanks a lot for this github,
floyd

**Comment by rodykersten** [comment]
Thanks for reporting these bugs you found, very interesting! Could you e-mail me the input files for the first one? And also good to know the tool works on ARM!

As for your question: JVM crashes are currently not detected. I haven't tested this, but I believe it would result in a time-out in AFL. I don't see a straight-forward implementation for this at the moment, as crashing the JVM means crashing the Java side component of Kelinci.

**Comment by floyd-fuh** [comment]
Hi Rody,

Maybe you want to join the afl-users mailing list? I've made a post about Kelinci https://groups.google.com/forum/#!topic/afl-users/L_YmC6UFJXU maybe you want to say hi on the mailing list or so

The input files can be found on the official page of AFL, here: http://lcamtuf.coredump.cx/afl/demo/

Ah, I see, so hunting for JVM bugs and/or native code is not an option then. Btw. the code itself is mainly unusable, but I've written down some ideas about Java fuzzing here: https://github.com/floyd-fuh/AFL_GCJ_Fuzzing_Simple (I'm planning to update the README today, I have some new ideas). And as you see on the mailing list, there is also another Java-AFL approach project here if you are interested: https://github.com/rohanpadhye/jqf

**Comment by floyd-fuh** [comment]
Btw. the issue leading to ArrayIndexOutOfBoundsException is now on https://issues.apache.org/jira/browse/IMAGING-215

**Comment by rodykersten** [comment]
Thanks for reporting the issue, promoting the tool and pointing me to the other works. I was familiar with the GCJ approach, but as you also write, GCJ is not really usable anymore. JQF looks interesting!
